### ISSUE TITLE
Table headers change size depending on dates in rows

### ISSUE THREAD

**Issue by SheyDenis** [FatCatProject/FatCat_Server#92] opened 2017-11-10 16:39 UTC
If you select a different page or date in a table, and the new page has a longer / shorter "longest date" (or any other column) than the previous page, then the table header will adjust it's size.
This is probably caused because the columns them selves adjust their size.

Currently happens in catPage.blade.php but probably affects other tables too.

**Comment by Shabnata** [comment] 2017-11-14 10:35
By design won't fix

**Closed as completed** 2017-11-14 10:35 UTC
Labels: invalid, wontfix
